---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, BROR, CBSE, CBRE, CGRR, EBDL, EBKR, SCMT, SREM 
summary: 'Si consiglia di acquisire familiarità con i messaggi di audit appartenenti alla categoria di audit dello storage a oggetti. Si tratta di eventi correlati allo storage e alla gestione di oggetti all"interno del sistema StorageGRID. Tra cui storage a oggetti e recuperi, trasferimenti da grid-node a grid-node e verifiche.' 
---
= Messaggi di audit dello storage a oggetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di audit appartenenti alla categoria di audit dello storage a oggetti vengono utilizzati per gli eventi correlati allo storage e alla gestione degli oggetti all'interno del sistema StorageGRID. Tra cui storage a oggetti e recuperi, trasferimenti da grid-node a grid-node e verifiche.

[cols="1a,2a,1a"]
|===
| Codice | Descrizione | Vedere 


 a| 
APCT
 a| 
Eliminazione dell'archivio dal livello cloud: I dati degli oggetti archiviati vengono cancellati da un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
link:apct-archive-purge-from-cloud-tier.html["APCT: Eliminazione dell'archivio dal Cloud-Tier"]



 a| 
ARCB
 a| 
Archive Object Retrieve Begin (inizio recupero oggetto archivio): Il servizio ARC avvia il recupero dei dati oggetto dal sistema di storage di archiviazione esterno.
 a| 
link:arcb-archive-object-retrieve-begin.html["ARCB: Inizio recupero oggetto archivio"]



 a| 
ARCE
 a| 
Archive Object Retrieve End (fine recupero oggetto archivio): I dati dell'oggetto sono stati recuperati da un sistema di storage di archiviazione esterno e il servizio ARC segnala lo stato dell'operazione di recupero.
 a| 
link:arce-archive-object-retrieve-end.html["ARCE: Fine recupero oggetto archivio"]



 a| 
ARCT
 a| 
Recupero archivio dal livello cloud: I dati degli oggetti archiviati vengono recuperati da un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
link:arct-archive-retrieve-from-cloud-tier.html["ARCT: Recupero archivio da Cloud-Tier"]



 a| 
AREM
 a| 
Archive Object Remove (Rimozione oggetto archivio): Un blocco di contenuto è stato eliminato correttamente o senza successo dal sistema di storage di archiviazione esterno.
 a| 
link:arem-archive-object-remove.html["AREM: Rimozione dell'oggetto di archiviazione"]



 a| 
ASCE
 a| 
Archive Object Store End (fine archivio oggetti): Un blocco di contenuto è stato scritto nel sistema di storage di archiviazione esterno e il servizio ARC segnala lo stato dell'operazione di scrittura.
 a| 
link:asce-archive-object-store-end.html["ASCE: Fine archivio oggetti"]



 a| 
ASTT
 a| 
Livello cloud archivio: I dati degli oggetti vengono memorizzati in un sistema storage di archiviazione esterno, che si connette a StorageGRID tramite l'API S3.
 a| 
link:asct-archive-store-cloud-tier.html["ASCT: Archivio Store Cloud-Tier"]



 a| 
ATCE
 a| 
Archive Object Store Begin (inizio archivio: Scrittura di un blocco di contenuto in uno storage di archiviazione esterno).
 a| 
link:atce-archive-object-store-begin.html["ATCE: Inizio archivio oggetti"]



 a| 
AVCC
 a| 
Archive Validate Cloud-Tier Configuration (convalida archivio configurazione livello cloud): Le impostazioni dell'account e del bucket fornite sono state validate correttamente o senza successo.
 a| 
link:avcc-archive-validate-cloud-tier-configuration.html["AVCC: Convalida archivio configurazione Cloud-Tier"]



 a| 
BROR
 a| 
Bucket Read Only Request (richiesta di sola lettura bucket): Un bucket è entrato o è uscito dalla modalità di sola lettura.
 a| 
link:bror-bucket-read-only-request.html["BROR: Richiesta di sola lettura bucket"]



 a| 
CBSE
 a| 
Object Send End (fine invio oggetto): L'entità di origine ha completato un'operazione di trasferimento dei dati dal nodo griglia al nodo griglia.
 a| 
link:cbse-object-send-end.html["CBSE: Fine invio oggetto"]



 a| 
CBRE
 a| 
Object Receive End (fine ricezione oggetto): L'entità di destinazione ha completato un'operazione di trasferimento dei dati dal nodo griglia al nodo griglia.
 a| 
link:cbre-object-receive-end.html["CBRE: Fine ricezione oggetto"]



 a| 
CGRR
 a| 
Richiesta di replica cross-grid: StorageGRID ha tentato un'operazione di replica cross-grid per replicare gli oggetti tra bucket in una connessione a federazione di grid.
 a| 
link:cgrr-cross-grid-replication-request.html["CGRR: Richiesta di replica cross-grid"]



 a| 
EBDL
 a| 
Empty bucket Delete (Elimina bucket vuoto): Lo scanner ILM ha eliminato un oggetto in un bucket che sta eliminando tutti gli oggetti (eseguendo un'operazione bucket vuoto).
 a| 
link:ebdl-empty-bucket-delete.html["EBDL: Eliminazione bucket vuoto"]



 a| 
EBKR
 a| 
Empty bucket Request (richiesta bucket vuoto): Un utente ha inviato una richiesta per attivare o disattivare il bucket vuoto (ovvero per eliminare oggetti bucket o per interrompere l'eliminazione di oggetti).
 a| 
link:ebkr-empty-bucket-request.html["EBKR: Richiesta bucket vuoto"]



 a| 
SCMT
 a| 
Commit dell'archivio oggetti: Un blocco di contenuto è stato completamente memorizzato e verificato e può essere richiesto.
 a| 
link:scmt-object-store-commit.html["SCMT: Richiesta di commit dell'archivio di oggetti"]



 a| 
SREM
 a| 
Rimozione archivio oggetti: Un blocco di contenuto è stato cancellato da un nodo griglia e non può più essere richiesto direttamente.
 a| 
link:srem-object-store-remove.html["SREM: Rimozione dell'archivio di oggetti"]

|===