---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11,8 utilizza la versione 4 dell"API di gestione dei tenant. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11,8 utilizza la versione 4 dell'API di gestione dei tenant. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare le versioni obsolete dell'API di gestione dei tenant con StorageGRID 11,8; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una versione futura di StorageGRID. Dopo l'aggiornamento a StorageGRID 11,8, è possibile disattivare le API obsolete utilizzando `PUT /grid/config/management` API.

Per ulteriori informazioni, visitare il sito Web all'indirizzo link:../tenant/understanding-tenant-management-api.html["Comprendere l'API di gestione dei tenant"].



== Nuovi endpoint per i tag dei criteri ILM

È possibile utilizzare gli endpoint dell'API */org/ilm-policy-tags* e */org/containers/{bucketName}/ilm-policy-tags* per eseguire operazioni correlate ai tag dei criteri ILM.
