---
permalink: ubuntu/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: Il pacchetto DEB di StorageGRID viene utilizzato per installare i servizi host di StorageGRID. 
---
= Installare i servizi host StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il pacchetto DEB di StorageGRID viene utilizzato per installare i servizi host di StorageGRID.

.A proposito di questa attività
Queste istruzioni descrivono come installare i servizi host dai pacchetti DEB. In alternativa, è possibile utilizzare i metadati del repository APT inclusi nell'archivio di installazione per installare i pacchetti DEB in remoto. Consultare le istruzioni del repository APT per il sistema operativo Linux in uso.

.Fasi
. Copiare i pacchetti DEB di StorageGRID su ciascuno degli host o renderli disponibili sullo storage condiviso.
+
Ad esempio, inserirli in `/tmp` directory, in modo da poter utilizzare il comando di esempio nel passaggio successivo.

. Accedere a ciascun host come root o utilizzando un account con autorizzazione sudo ed eseguire i seguenti comandi.
+
È necessario installare `images` prima il pacchetto e il `service` pacchetto secondo. Se i pacchetti sono inseriti in una directory diversa da `/tmp`, modificare il comando in modo che rifletta il percorso utilizzato.

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: Python 2.7 deve essere già installato prima di poter installare i pacchetti StorageGRID. Il `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` il comando non riuscirà fino a quando non sarà stato fatto.


