---
permalink: harden/index.html 
sidebar: sidebar 
keywords: Hardening guidelines, system, security 
summary: La protezione avanzata del sistema è il processo che consente di eliminare il maggior numero possibile di rischi per la sicurezza da un sistema StorageGRID. 
---
= Protezione avanzata del sistema: Panoramica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La protezione avanzata del sistema è il processo che consente di eliminare il maggior numero possibile di rischi per la sicurezza da un sistema StorageGRID.

Questo documento fornisce una panoramica delle linee guida per la protezione avanzata specifiche di StorageGRID. Queste linee guida integrano le Best practice standard di settore per la protezione avanzata dei sistemi. Ad esempio, queste linee guida presuppongono l'utilizzo di password complesse per StorageGRID, l'utilizzo di HTTPS invece di HTTP e l'attivazione dell'autenticazione basata su certificato, se disponibile.

Durante l'installazione e la configurazione di StorageGRID, è possibile utilizzare queste linee guida per soddisfare qualsiasi obiettivo di sicurezza prescritto in termini di riservatezza, integrità e disponibilità del sistema informativo.

StorageGRID segue il https://security.netapp.com/policy/["Policy di gestione delle vulnerabilità di NetApp"^]. Le vulnerabilità segnalate vengono verificate e risolte in base al processo di risposta agli incidenti di sicurezza del prodotto.



== Considerazioni generali per la protezione avanzata dei sistemi StorageGRID

Quando si esegue la protezione avanzata di un sistema StorageGRID, è necessario considerare quanto segue:

* Quale delle tre reti StorageGRID è stata implementata? Tutti i sistemi StorageGRID devono utilizzare la rete griglia, ma è possibile utilizzare anche la rete di amministrazione, la rete client o entrambi. Ogni rete ha considerazioni di sicurezza diverse.
* Il tipo di piattaforme utilizzate per i singoli nodi nel sistema StorageGRID. I nodi StorageGRID possono essere implementati su macchine virtuali VMware, all'interno di un motore di container su host Linux o come appliance hardware dedicate. Ogni tipo di piattaforma dispone di un proprio set di Best practice per la protezione avanzata.
* Quanto sono affidabili gli account tenant. Se sei un provider di servizi con account tenant non attendibili, avrai problemi di sicurezza diversi rispetto all'utilizzo di tenant interni affidabili.
* Quali requisiti e convenzioni di sicurezza sono seguiti dalla tua organizzazione. Potrebbe essere necessario rispettare requisiti normativi o aziendali specifici.

