---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: È necessario scaricare gli archivi di installazione di StorageGRID ed estrarre i file. 
---
= Scaricare ed estrarre i file di installazione di StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario scaricare gli archivi di installazione di StorageGRID ed estrarre i file.

.Fasi
. Accedere alla https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Pagina dei download NetApp per StorageGRID"^].
. Selezionare il pulsante per scaricare l'ultima versione oppure selezionare un'altra versione dal menu a discesa e selezionare *Go*.
. Accedi con il nome utente e la password del tuo account NetApp.
. Se viene visualizzata un'istruzione Caution/MustRead, leggerla e selezionare la casella di controllo.
+

CAUTION: Dopo aver installato la release di StorageGRID, è necessario applicare le correzioni rapide richieste. Per ulteriori informazioni, consultare link:../maintain/storagegrid-hotfix-procedure.html["procedura di hotfix nelle istruzioni di ripristino e manutenzione"]

. Leggere il Contratto di licenza con l'utente finale, selezionare la casella di controllo, quindi selezionare *Accept & Continue* (Accetta e continua).
. Nella colonna *Installa StorageGRID*, selezionare il file .tgz o .zip per VMware.
+

NOTE: Utilizzare `.zip` File se si esegue Windows sul laptop di assistenza.

. Salvare ed estrarre il file di archivio.
. Scegliere i file desiderati dal seguente elenco.
+
I file necessari dipendono dalla topologia di griglia pianificata e dal modo in cui verrà implementato il sistema StorageGRID.




NOTE: I percorsi elencati nella tabella sono relativi alla directory di primo livello installata dall'archivio di installazione estratto.

[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./vsphere/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
Il file del disco della macchina virtuale utilizzato come modello per la creazione di macchine virtuali con nodo grid.



| ./vsphere/vsphere-primary-admin.ovf

./vsphere/vsphere-primary-admin.mf  a| 
Il file di modello Open Virtualization Format (`.ovf`) e il file manifest (`.mf`) Per l'implementazione del nodo di amministrazione primario.



| ./vsphere/vsphere-non-primary-admin.ovf

./vsphere/vsphere-non-primary-admin.mf  a| 
Il file di modello (`.ovf`) e il file manifest (`.mf`) Per l'implementazione di nodi amministrativi non primari.



| ./vsphere/vsphere-archive.ovf

./vsphere/vsphere-archive.mf  a| 
Il file di modello (`.ovf`) e il file manifest (`.mf`) Per l'implementazione dei nodi di archiviazione.



| ./vsphere/vsphere-gateway.ovf

./vsphere/vsphere-gateway.mf  a| 
Il file di modello (`.ovf`) e il file manifest (`.mf`) Per l'implementazione dei nodi gateway.



| ./vsphere/vsphere-storage.ovf

./vsphere/vsphere-storage.mf  a| 
Il file di modello (`.ovf`) e il file manifest (`.mf`) Per l'implementazione di nodi di storage basati su macchine virtuali.



| Tool di scripting per la distribuzione | Descrizione 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Uno script della shell Bash utilizzato per automatizzare l'implementazione dei nodi virtual grid.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Un file di configurazione di esempio da utilizzare con `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando è attivato il Single Sign-on (SSO). È anche possibile utilizzare questo script per il ping federate.



| ./vsphere/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` script.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` script.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Script di supporto chiamato dal compagno `storagegrid-ssoauth-azure.py` Script Python per eseguire interazioni SSO con Azure.



| ./vsphere/extra/schemi api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===