---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: red hat linux installation files, how to download installation files 
summary: 'È necessario scaricare l"archivio di installazione di StorageGRID ed estrarre i file richiesti.' 
---
= Scaricare ed estrarre i file di installazione di StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario scaricare l'archivio di installazione di StorageGRID ed estrarre i file richiesti.

.Fasi
. Accedere alla https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Pagina dei download NetApp per StorageGRID"^].
. Selezionare il pulsante per scaricare l'ultima versione oppure selezionare un'altra versione dal menu a discesa e selezionare *Go*.
. Accedi con il nome utente e la password del tuo account NetApp.
. Se viene visualizzata un'istruzione Caution/MustRead, leggerla e selezionare la casella di controllo.
+

CAUTION: Dopo aver installato la release di StorageGRID, è necessario applicare le correzioni rapide richieste. Per ulteriori informazioni, consultare link:../maintain/storagegrid-hotfix-procedure.html["procedura di hotfix nelle istruzioni di ripristino e manutenzione"].

. Leggere il Contratto di licenza con l'utente finale, selezionare la casella di controllo, quindi selezionare *Accept & Continue* (Accetta e continua).
. Nella colonna *Installa StorageGRID*, selezionare il file .tgz o .zip per Red Hat Enterprise Linux.
+

NOTE: Selezionare `.zip` File se si esegue Windows sul laptop di assistenza.

. Salvare ed estrarre il file di archivio.
. Scegliere i file desiderati dal seguente elenco.
+
I file necessari dipendono dalla topologia di griglia pianificata e dal modo in cui verrà implementato il sistema StorageGRID.

+

NOTE: I percorsi elencati nella tabella sono relativi alla directory di primo livello installata dall'archivio di installazione estratto



[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./rpms/README  a| 
Un file di testo che descrive tutti i file contenuti nel file di download di StorageGRID.



| ./rpms/NLF000000.txt  a| 
Licenza gratuita che non fornisce alcun diritto di supporto per il prodotto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione delle immagini del nodo StorageGRID sui vostri host RHEL.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacchetto RPM per l'installazione del servizio host StorageGRID sugli host RHEL.



| Tool di scripting per la distribuzione | Descrizione 


| ./rpms/configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Script Python utilizzato per automatizzare la configurazione delle appliance StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` script.



| ./rpms/storagegrid-ssoauth.py  a| 
Script Python di esempio che è possibile utilizzare per accedere all'API Grid Management quando è attivato il single sign-on. È anche possibile utilizzare questo script per il ping federate.



| ./rpms/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` script.



| ./rpms/extra/ansible  a| 
Esempio di ruolo e playbook Ansible per la configurazione degli host RHEL per l'implementazione dei container StorageGRID. È possibile personalizzare il ruolo o il manuale in base alle esigenze.



| ./rpms/storagegrid-ssoauth-azure.py  a| 
Esempio di script Python che è possibile utilizzare per accedere all'API Grid Management quando SSO (Single Sign-on) è attivato utilizzando Active Directory o Ping Federate.



| ./rpms/storagegrid-ssoauth-azure.js  a| 
Script di supporto chiamato dal compagno `storagegrid-ssoauth-azure.py` Script Python per eseguire interazioni SSO con Azure.



| ./rpms/extra/schemi-api  a| 
Schemi API per StorageGRID.

*Nota*: Prima di eseguire un aggiornamento, è possibile utilizzare questi schemi per confermare che qualsiasi codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova release di StorageGRID se non si dispone di un ambiente StorageGRID non in produzione per il test di compatibilità degli aggiornamenti.

|===