---
permalink: admin/adding-nfs-audit-client-to-audit-share.html 
sidebar: sidebar 
keywords: nfs, audit client, audit share 
summary: 'Ai client di audit NFS viene concesso l"accesso a una condivisione di audit in base al proprio indirizzo IP. Concedere l"accesso alla condivisione di audit a un nuovo client di audit NFS aggiungendo il proprio indirizzo IP alla condivisione di audit.' 
---
= Aggiungere un client di audit NFS a una condivisione di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ai client di audit NFS viene concesso l'accesso a una condivisione di audit in base al proprio indirizzo IP. Concedere l'accesso alla condivisione di audit a un nuovo client di audit NFS aggiungendo il proprio indirizzo IP alla condivisione di audit.


NOTE: Il supporto per NFS è stato obsoleto e verrà rimosso in una versione futura.

.Prima di iniziare
* Hai il `Passwords.txt` file con la password dell'account root/admin.
* Hai il `Configuration.txt` File (disponibile nel pacchetto di ripristino).
* Il client di audit utilizza NFS versione 3 (NFSv3).


.Fasi
. Accedere al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



. Avviare l'utility di configurazione NFS: `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. Inserire: `add-ip-to-share`
+
Viene visualizzato un elenco di condivisioni di controllo NFS attivate nel nodo di amministrazione. La condivisione dell'audit è elencata come: `/var/local/log`

. Inserire il numero della condivisione di controllo: `_audit_share_number_`
. Quando richiesto, inserire l'indirizzo IP o l'intervallo di indirizzi IP del client di controllo per la condivisione di controllo: `_client_IP_address_`
+
Il client di audit viene aggiunto alla condivisione di audit.

. Quando richiesto, premere *Invio*.
+
Viene visualizzata l'utility di configurazione NFS.

. Ripetere i passaggi per ogni client di audit da aggiungere alla condivisione di audit.
. In alternativa, verificare la configurazione: `validate-config`
+
I servizi vengono controllati e visualizzati.

+
.. Quando richiesto, premere *Invio*.
+
Viene visualizzata l'utility di configurazione NFS.



. Chiudere l'utility di configurazione NFS: `exit`
. Se l'implementazione di StorageGRID è un singolo sito, passare alla fase successiva.
+
In caso contrario, se l'implementazione di StorageGRID include nodi di amministrazione in altri siti, attivare facoltativamente queste condivisioni di controllo come richiesto:

+
.. Accedere in remoto al nodo di amministrazione di un sito:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.


.. Ripetere questa procedura per configurare le condivisioni di controllo per ciascun nodo di amministrazione.
.. Chiudere l'accesso remoto sicuro alla shell nel nodo di amministrazione remoto: `exit`


. Disconnettersi dalla shell dei comandi: `exit`

