---
permalink: monitor/viewing-manage-drives-tab.html 
sidebar: sidebar 
keywords: Manage drives tab, hardware diagnostics, fail drive, logically replace drive 
summary: 'La scheda Manage Drives (Gestisci dischi) consente di accedere ai dettagli ed eseguire le attività di troubleshooting e manutenzione dei dischi dell"appliance SGF6112.' 
---
= Visualizza la scheda Gestisci unità (solo SGF6112)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La scheda Manage Drives (Gestisci dischi) consente di accedere ai dettagli ed eseguire le attività di troubleshooting e manutenzione dei dischi dell'appliance SGF6112.


NOTE: La scheda Gestisci dischi è disponibile solo per SGF6112 nodi di appliance di storage.

Utilizzando la scheda Gestisci unità, è possibile effettuare le seguenti operazioni:

* Visualizzare un layout delle unità di storage dei dati nell'appliance
* Visualizza una tabella in cui sono elencati ogni tipo, posizione, stato, versione del firmware e numero di serie del disco
* Eseguire le funzioni di risoluzione dei problemi e manutenzione su ciascuna unità


Per accedere alla scheda Gestisci unità, è necessario disporre di link:../admin/admin-group-permissions.html["Autorizzazione di accesso root o amministratore dell'appliance di storage"].

Per informazioni sull'utilizzo della scheda Gestisci unità, vedere https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/manage-drives-tab.html["Utilizzare la scheda Gestisci unità"^].
