---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: È necessario completare una serie di attività per ripristinare un nodo di storage basato su software in cui uno o più volumi di storage sul nodo di storage si sono guastati, ma il disco di sistema è intatto. Se solo i volumi di storage sono guasti, il nodo di storage è ancora disponibile per il sistema StorageGRID. 
---
= Eseguire il ripristino da un errore del volume di storage in cui l'unità di sistema è intatta: Panoramica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario completare una serie di attività per ripristinare un nodo di storage basato su software in cui uno o più volumi di storage sul nodo di storage si sono guastati, ma il disco di sistema è intatto. Se solo i volumi di storage sono guasti, il nodo di storage è ancora disponibile per il sistema StorageGRID.


NOTE: Questa procedura di ripristino si applica solo ai nodi di storage basati su software. Se i volumi di storage si sono guastati su un nodo di storage dell'appliance, utilizzare la procedura dell'appliance: link:recovering-storagegrid-appliance-storage-node.html["Ripristinare il nodo storage dell'appliance"].

Questa procedura di ripristino include le seguenti attività:

* link:reviewing-warnings-about-storage-volume-recovery.html["Esaminare gli avvisi per il ripristino del volume di archiviazione"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identificare e smontare i volumi di storage guasti"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Recuperare i volumi e ricostruire il database Cassandra"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Ripristinare i dati degli oggetti"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Controllare lo stato di memorizzazione"]

