---
permalink: maintain/restoring-admin-node-database-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, primary admin node 
summary: Se si desidera conservare le informazioni cronologiche relative ad attributi, allarmi e avvisi su un nodo di amministrazione primario che ha avuto esito negativo, è possibile ripristinare il database del nodo di amministrazione. È possibile ripristinare questo database solo se il sistema StorageGRID include un altro nodo amministratore. 
---
= Ripristinare il database Admin Node durante il ripristino del nodo Admin primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera conservare le informazioni cronologiche relative ad attributi, allarmi e avvisi su un nodo di amministrazione primario che ha avuto esito negativo, è possibile ripristinare il database del nodo di amministrazione. È possibile ripristinare questo database solo se il sistema StorageGRID include un altro nodo amministratore.

.Prima di iniziare
* Il nodo Admin recuperato è installato e in esecuzione.
* Il sistema StorageGRID include almeno due nodi di amministrazione.
* Hai il `Passwords.txt` file.
* Si dispone della passphrase di provisioning.


.A proposito di questa attività
In caso di errore di un nodo amministratore, le informazioni storiche memorizzate nel database del nodo amministratore andranno perse. Questo database include le seguenti informazioni:

* Cronologia degli avvisi
* Cronologia degli allarmi
* Dati storici degli attributi, utilizzati nei grafici e nei report di testo disponibili nella pagina *SUPPORTO* > *Strumenti* > *topologia griglia*.


Quando si ripristina un nodo amministratore, il processo di installazione del software crea un database Admin Node vuoto sul nodo recuperato. Tuttavia, il nuovo database include solo le informazioni relative ai server e ai servizi attualmente presenti nel sistema o aggiunti successivamente.

Se è stato ripristinato un nodo di amministrazione primario e il sistema StorageGRID dispone di un altro nodo di amministrazione, è possibile ripristinare le informazioni storiche copiando il database del nodo di amministrazione da un nodo di amministrazione non primario (il _nodo di amministrazione di origine_) al nodo di amministrazione primario recuperato. Se il sistema dispone solo di un nodo di amministrazione primario, non è possibile ripristinare il database del nodo di amministrazione.


NOTE: La copia del database Admin Node potrebbe richiedere diverse ore. Alcune funzionalità di Grid Manager non saranno disponibili mentre i servizi vengono arrestati sul nodo di amministrazione di origine.

.Fasi
. Accedere al nodo di amministrazione di origine:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


. Dal nodo Admin di origine, arrestare il servizio MI: `service mi stop`
. Dal nodo di amministrazione di origine, arrestare il servizio Management Application Program Interface (mgmt-api): `service mgmt-api stop`
. Completare i seguenti passaggi sul nodo di amministrazione ripristinato:
+
.. Accedere al nodo di amministrazione recuperato:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.


.. Arrestare il servizio MI: `service mi stop`
.. Arrestare il servizio mgmt-api: `service mgmt-api stop`
.. Aggiungere la chiave privata SSH all'agente SSH. Inserire:``ssh-add``
.. Inserire la password di accesso SSH elencata in `Passwords.txt` file.
.. Copiare il database dal nodo Admin di origine al nodo Admin recuperato: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Quando richiesto, confermare che si desidera sovrascrivere il database MI nel nodo Admin recuperato.
+
Il database e i relativi dati storici vengono copiati nel nodo di amministrazione recuperato. Al termine dell'operazione di copia, lo script avvia il nodo Admin recuperato.

.. Se non si richiede più l'accesso senza password ad altri server, rimuovere la chiave privata dall'agente SSH. Inserire:``ssh-add -D``


. Riavviare i servizi sul nodo di amministrazione di origine: `service servermanager start`

