---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Potrebbe essere necessario riavviare il server manager e tutti i servizi in esecuzione su un nodo grid. 
---
= Riavviare Server Manager e tutti i servizi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario riavviare il server manager e tutti i servizi in esecuzione su un nodo grid.

.Prima di iniziare
Hai il `Passwords.txt` file.

.Fasi
. Accedere al nodo Grid:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.

. Riavviare Server Manager e tutti i servizi sul nodo grid: `service servermanager restart`
+
Server Manager e tutti i servizi sul nodo grid vengono arrestati e quindi riavviati.

+

NOTE: Utilizzando il `restart` il comando è identico a quello utilizzato da `stop` seguito dal comando `start` comando.

. Disconnettersi dalla shell dei comandi: `exit`

